server:
  port: 8082

spring:
  application:
    name: service2-greeting

# Logging
logging:
  level:
    com.microservice.greeting: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-}] %logger{36} - %msg%n"

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Server configuration
  servlet:
    context-path: /
  error:
    include-message: always